Addition of the XSD 1.1 validator to allow for Conditional Type Assignment
idaholab/raven pull request #1501
Opened 2021-04-07 00:00 UTC by alfoa

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #1500

##### What are the significant changes in functionality due to this change request?
Addition of the library  ```xmlschema``` that allows for validation of XSD version 1.1.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-04-07 15:29 UTC, PaulTalbot-INL commented
The documentation (https://www.w3.org/TR/xmlschema11-1/#cTypeAlternative) seems fairly painful to parse without being an expert, but hopefully we can make it do what we want. It would be nice to see that this works for what we need before adding the dependency; can we see it in our XSD?

2021-04-07 15:32 UTC, PaulTalbot-INL requested changes
Only one non-conforming variable to fix.

2021-04-07 15:32 UTC, PaulTalbot-INL commented on developer_tools/validate_xml.py
> +  my_schema = xmlschema.XMLSchema11(schema)
this should be `mySchema`

2021-10-29 23:29 UTC, wangcj05 commented on developer_tools/validate_xml.py
> +  my_schema = xmlschema.XMLSchema11(schema)
changed.

2021-10-29 23:30 UTC, wangcj05 commented
I have updated this branch, and it seems it works well. @PaulTalbot-INL @joshua-cogliati-inl @mandd do you have any comments?

2021-11-01 16:33 UTC, joshua-cogliati-inl commented
I have no objections to switching to a different validator (with the comment that we really need to finish getting InputData used everywhere).

2021-11-01 16:45 UTC, wangcj05 commented
As we discussed today, I think we all agreed we can update XSD to 1.1, and we will push the fully deployment of InputData for RAVEN. @PaulTalbot-INL do you have any comments for this PR? I saw you have reviewed it in the past.

2021-11-01 16:55 UTC, wangcj05 approved these changes

2021-11-03 16:49 UTC, mandd approved these changes

2021-11-04 05:02 UTC, wangcj05 commented
Checklist is satisfied, and PR have been approved by another developer. This PR can be merged.

2021-11-04 05:03 UTC, merged