Adding DSS capabilities
idaholab/raven pull request #1619
Opened 2021-07-21 22:30 UTC by yoshiurr-INL

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #1617

##### What are the significant changes in functionality due to this change request?
- The main function of this pull request is to add Dynamical System Scaling (DSS) to wangc/validation_pp_base.
- The addition of metric and postprocessor DSS code is part of the PR.
- To pass DSS specific data to metric code DSS, the MetricDistributor.py has been modified. When "DSS" is added as the metric in the xml file, the modified code will pass postprossed data to only the DSS metric code.
- Test files showing the DSS functionality is added as well.
----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-07-25 16:14 UTC, Jimmy-INL commented on framework/Models/PostProcessors/validationAlgorithms/PPDSS.py
> +    # the input can be either be a list of dataobjects or a list of datasets (xarray)
These asserts will error out!
If they are necessary, maybe `assert(isinstance(inputIn['Data][0][-1],xr.Dataset))` ?

2021-07-27 15:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/784690/) on 07da9b7 : invalidated by @joshua-cogliati-inl

checking civet.

2021-07-28 17:54 UTC, Jimmy-INL commented on framework/Models/PostProcessors/validationAlgorithms/PPDSS.py
> +    assert(isinstance(inputIn["Data"][0][-1], xr.Dataset) and isinstance(inputI["Data"][1][-1], xr.Dataset))
There is a missing `n` in `inpoutI['Data'][1][-1]`

2021-07-28 17:59 UTC, Jimmy-INL commented on framework/Models/PostProcessors/validationAlgorithms/PPDSS.py
> +    assert(isinstance(inputIn["Data"][0][-1], xr.Dataset) and isinstance(inputI["Data"][1][-1], xr.Dataset))
I tried to push it my self but it gave me:
`remote: Password authentication is temporarily disabled as part of a brownout. Please use a personal access token instead.
remote: Please see https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/ for more information.
fatal: unable to access 'https://github.com/idaholab/raven.git/': The requested URL returned error: 403`

2021-09-29 01:49 UTC, wangcj05 commented
@yoshiurr-INL Can you rebase your branch with devel and try to resolve the conflicts?

2021-10-18 16:19 UTC, wangcj05 commented
@yoshiurr-INL @Jimmy-INL This branch has been cleaned up.

2021-11-01 15:01 UTC, yoshiurr-INL commented
> @yoshiurr-INL Is it ready to be reviewed?

I will finish the documentation today. Afterwards, it should be ready for review.

2021-11-07 18:11 UTC, wangcj05 requested changes
@yoshiurr-INL I have several comments for your consideration. In addition:
1. Please clean up the csv files in both DSS and gold/DSS folders 
2. Please update "tests" file with DSS, otherwise your test will not be tested by the machine
3. Please update the manual with some detailed information or add a user guide in another PR
4. please remove print statement, commented lines, and use camelback instead of underscores for the variables.

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +#from Models.PostProcessors import PostProcessor
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #inputSpecification.addSub(targetsInput)
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    # Have added the new pivotParameters for feature and target. The original has been commented out.
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #inputSpecification.addSub(metricInput)
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    scaleRatioOmegaInput = InputData.parameterInputFactory("scaleOmega", contentType=InputTypes.FloatListType)
please use "descr" key words to add the descriptions for each node, and attribute in the XML.

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #self.metricsDict           = {}    # dictionary of metrics that are going to be assembled
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #self.pivotValues           = []
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #self.scaleType             = ['DataSynthesis','2_2_Affine','Dilation','beta_strain','omega_strain','identity']
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #self.addAssemblerObject('Metric', InputData.Quantity.one_to_infinity)
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +        #self.featuresType = child.parameterValues['type']
remove?

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #  self.raiseAnError(IOError, 'The number of variables found in XML node "Features" is not equal the number of variables found in XML node "Targets"')
remove the commented codes

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #print("inputIn['Data'][0][-1].indexes:",inputIn['Data'][0][-1].indexes)
remove the commented lines of codes

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    #print("datasets:",datasets)
remove this line

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +        z_count = targData.shape[1]
camelBack for y_count and z_count

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +        #print("featureOmega:",featureOmega)
remove

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +          track_count = 0
camelBack for the variables with underscore

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +        #print("featureInt_new:",featureInt_new)
Please remove all the print statement in the entire code

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +          track_count = 0
please change the variables using underscore to camelBack for the entire file

2021-11-07 18:11 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +  def _getDataFromDatasets(self, datasets, var, names=None):
Is it function used by other post-processors, like "Probabilistic"? If so, please move it to the Validation base class

2021-11-08 16:57 UTC, yoshiurr-INL commented on doc/user_manual/metrics.tex
> +This XML node needs to contain the attributes:
Fixed

2021-11-08 23:20 UTC, moosebuild commented
Job [Test Fedora 31](https://civet.inl.gov/job/879092/) on cbc7fe1 : invalidated by @wangcj05

retesting

2021-11-08 23:53 UTC, moosebuild commented
Job [Test Fedora 32](https://civet.inl.gov/job/879093/) on cbc7fe1 : invalidated by @Jimmy-INL

2021-11-11 16:49 UTC, yoshiurr-INL commented on doc/user_manual/postprocessor.tex
> +          \item \textbf{identity}, calculating the distortion for two data sets with scaling ratios of 1.
Made new section in raven theory manual to aid the comprehension of DSS. Scaling type are noted in that specific section.

2021-11-17 22:28 UTC, wangcj05 commented on doc/theory_manual/raven_theory_manual.tex
> +\input{dssPostProcessor.tex}
This file is not uploaded to your remote branch.

2021-11-18 16:59 UTC, wangcj05 requested changes
@yoshiurr-INL I have some additional comments for your consideration. In addition:
1. there is a missing .tex file for theory manual 
2. I am wondering if you can desire a analytic test case for DSS in future PR.

2021-11-18 16:59 UTC, wangcj05 commented on doc/user_manual/metrics.tex
> +This XML node needs to contain the attributes:
It seems 'attributes' is still used.

2021-11-18 16:59 UTC, wangcj05 commented on doc/user_manual/metrics.tex
> +      <actionType>DataSynthetic</actionType>
I think you have removed this node, right? It is not defined in the getInputSpecification.

2021-11-18 16:59 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    scaleTypeInput = InputData.parameterInputFactory("scale", contentType=InputTypes.StringType,
Please try to use ```InputTypes.makeEnumType``` to define a new type for scale parameter, see the following for an example:
![image](https://user-images.githubusercontent.com/7321071/142457852-fd3cce6f-8355-405c-b6d9-71faa02a3eea.png)

2021-11-18 16:59 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +    self.scaleRatioOmega       = []
please provide comments for these self variables

2021-11-18 16:59 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +      #print(output)
remove print statement?

2021-11-18 16:59 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +        #print(newfeatureData[1][cnt])
remove this line

2021-11-18 16:59 UTC, wangcj05 commented on framework/Models/PostProcessors/Validations/PPDSS.py
> +      output.addRealization(rlz)
I think you can use the collectOutput method in "PostProcessorInterface.py" class with key word "self.outputMultipleRealizations = True" in "__init__" method.

2021-12-01 04:16 UTC, wangcj05 commented
@yoshiurr-INL There are some compiling issue with the theory manual, could you check that?

2021-12-02 05:15 UTC, moosebuild commented
Job [Test qsubs falcon](https://civet.inl.gov/job/904733/) on 9632050 : invalidated by @yoshiurr-INL

2021-12-02 23:06 UTC, wangcj05 approved these changes
This PR is good to me.

2021-12-06 15:46 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/905880/) on f81f692 : invalidated by @joshua-cogliati-inl

restarted civet

2021-12-06 16:04 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/905880/) on f81f692 : invalidated by @yoshiurr-INL

Need to restart checking process due to win-mingw was not restarted.

2021-12-06 18:05 UTC, merged