Update scikit learn
idaholab/raven pull request #1831
Opened 2022-05-18 20:35 UTC by joshua-cogliati-inl

--------
Pull Request Description
--------
##### What issue does this change request address?
#1679

##### What are the significant changes in functionality due to this change request?
Updates scikit learn to 0.24

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-05-18 23:31 UTC, dylanjm commented
@joshua-cogliati-inl I'm thinking the best bet would be to merge this first before fixing HERON. Since me updating the ARMA files will then break while using the devel version of RAVEN.

2022-05-19 13:30 UTC, moosebuild commented
Job [Test qsubs sawtooth](https://civet.inl.gov/job/1049211/) on acf5594 : invalidated by @joshua-cogliati-inl

FAILED: Diff tests/cluster_tests/AdaptiveSobol/test_parallel_adaptive_sobol

2022-05-19 14:55 UTC, joshua-cogliati-inl commented
FYI: Github is confused.  The tests have passed: https://civet.inl.gov/pr/15929/

2022-05-19 15:09 UTC, wangcj05 requested changes
I have some minor comments for your consideration.

2022-05-19 15:09 UTC, wangcj05 commented on tests/framework/PostProcessors/DataMiningPostProcessor/Clustering/test_dataMiningKMeans.xml
> +      <what>Output</what>
any specific reason for this modification?

2022-05-19 15:17 UTC, joshua-cogliati-inl commented on tests/framework/PostProcessors/CrossValidations/test_stratifiedKFold.xml
> -        <random_state>10</random_state>
Because random_state is now an error if shuffle is False (since random_state is only used when shuffle is True)

2022-05-19 15:34 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/1049643/) on 7a7f0f2 : invalidated by @joshua-cogliati-inl

changed civet

2022-05-19 15:37 UTC, joshua-cogliati-inl commented on ravenframework/SupervisedLearning/ScikitLearn/LinearModel/BayesianRidge.py
> +                                                 descr=r"""Initial value for lambda (precision of the weights).""", default=1.0))
Done.

2022-05-19 16:21 UTC, joshua-cogliati-inl commented
Suggested email:
Scikit-learn has been updated to 0.24 with the pull request https://github.com/idaholab/raven/pull/1831
This has two effects.  Due to some model changes, results can change for some RAVEN inputs that use scikit-learn models.
In addition, after updating RAVEN, establish conda will need to be run to switch to the new scikit-learn version:
`./scripts/establish_conda_env.sh --install`

2022-05-19 16:51 UTC, wangcj05 approved these changes
changes are good.

2022-05-19 17:43 UTC, moosebuild commented
Job [Test qsubs sawtooth](https://civet.inl.gov/job/1049740/) on 6995de8 : invalidated by @joshua-cogliati-inl

FAILED: Diff tests/cluster_tests/AdaptiveSobol/test_parallel_adaptive_sobol

2022-05-19 18:38 UTC, wangcj05 commented
Checklist is satisfied, and PR has been reviewed and approved.

2022-05-19 18:38 UTC, merged