[WIP] Adding GA to workshop
idaholab/raven pull request #1897
Opened 2022-07-19 01:30 UTC by Jimmy-INL

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-07-25 20:57 UTC, wangcj05 requested changes
I have a couple of comments. In addition,
1. Please open an issue for this PR
2. Please open another issue regarding the handling of solution export variables 
3. Please open an issue regarding dependent variables

2022-07-25 20:57 UTC, wangcj05 commented on ravenframework/Optimizers/GeneticAlgorithm.py
> +  def _resolveNewGeneration(self, traj, rlz, objectiveVal, fitness, g, info):
add docstring for "g"

2022-07-25 20:57 UTC, wangcj05 commented on ravenframework/Optimizers/RavenSampled.py
> +    # toExport.update(dict((var, rlz[var]) for var in self.dependentSample))
Let's put a if check here:
```Python
toExport.update(dict((var, rlz[var]) for var in self.dependentSample if var in rlz))
```

2022-07-25 20:57 UTC, wangcj05 commented on tests/framework/AnalyticModels/optimizing/projectileConstraints.py
> +    @ In, self, object, RAVEN container
update "self" to "Input"

2022-07-25 20:57 UTC, wangcj05 commented on tests/framework/AnalyticModels/optimizing/projectileConstraints.py
> +    @ In, self, object, RAVEN container
update "self" to "Input"

2022-07-25 20:57 UTC, wangcj05 commented on tests/framework/AnalyticModels/optimizing/projectileConstraints.py
> +  implicitConstraint = implicitConstraint(Input)
why both implicitConstraint and "Constraint" in the same file, I guess you will get some problem with it.

2022-07-26 04:05 UTC, Jimmy-INL commented
<img width="830" alt="Screen Shot 2022-07-25 at 9 54 53 PM" src="https://user-images.githubusercontent.com/52417034/180920671-2a535fd2-7bab-42a9-b52b-0d286ccb601c.png">

2022-07-26 04:12 UTC, Jimmy-INL commented
<img width="1160" alt="Screen Shot 2022-07-25 at 10 12 33 PM" src="https://user-images.githubusercontent.com/52417034/180921380-d521035a-b75c-4be9-b35f-49beb682283d.png">

2022-07-26 04:14 UTC, Jimmy-INL commented
<img width="855" alt="Screen Shot 2022-07-25 at 10 14 40 PM" src="https://user-images.githubusercontent.com/52417034/180921629-54a03cc0-5d0b-4a38-9090-03e5916aaad1.png">

2022-07-26 04:18 UTC, Jimmy-INL commented
<img width="861" alt="Screen Shot 2022-07-25 at 10 18 32 PM" src="https://user-images.githubusercontent.com/52417034/180922058-11dba475-99b1-4018-81fa-815651bc278b.png">

2022-07-26 04:19 UTC, Jimmy-INL commented
these are all the timed out tests

2022-07-26 04:24 UTC, wangcj05 approved these changes

2022-07-26 04:29 UTC, wangcj05 commented
PR looks good, tests passed on local machine. Regression test system is not available this week, PR will be retested once the test system is back. This PR is required for RAVEN workshop. As CCB, I approve this PR.

2022-07-26 04:29 UTC, merged