Mattdon/new melcor interface
idaholab/raven pull request #2017
Opened 2022-11-17 22:29 UTC by mandd

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2023-02-22 15:44 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/1367367/) on 3eb7f67 : invalidated by @joshua-cogliati-inl

restarted civet

2023-05-26 19:42 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1555091/) on d8c1ae7 : invalidated by @aalfonsi

2023-05-26 19:59 UTC, wangcj05 commented
> Job [Precheck](https://civet.inl.gov/job/1555091/) on [d8c1ae7](https://github.com/idaholab/raven/commit/d8c1ae77eb3124b0cf907a11f3094411f6cd0dcb) : invalidated by @aalfonsi

@mandd @aalfonsi FYI, pre-check failed due to hpcgithub issue. This may be resolved until next Tuesday.

2023-05-27 20:24 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1555091/) on d8c1ae7 : invalidated by @aalfonsi

2023-05-27 20:31 UTC, aalfonsi commented on ravenframework/Models/PostProcessors/SubdomainBasicStatistics.py
> +                        f "of the input space of DataObject {inputs[-1].name}!"))
```suggestion
                        f"of the input space of DataObject {inputs[-1].name}!"))
```

2023-06-02 22:05 UTC, mandd commented
@wangcj05 : this PR is good to be reviewed

2023-06-03 20:33 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/1566364/) on 851e8df : invalidated by @mandd

2023-06-03 20:33 UTC, moosebuild commented
Job [Test qsubs sawtooth](https://civet.inl.gov/job/1566363/) on 851e8df : invalidated by @mandd

2023-06-05 14:54 UTC, wangcj05 commented
@mandd Could you create an issue for this PR? In addition, could you update the description for this PR? I will review it this week.

2023-06-07 17:07 UTC, wangcj05 requested changes
@mandd I have a couple of comments for you to consider.

2023-06-07 17:07 UTC, wangcj05 commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +      if inputFile.getExt() in self.getInputExtension():
I do not see a function to add the input extension for this interface. I think you need to update the self.inputExtensions using setInputExtension method or using addDefaultExtension method.

2023-06-26 16:18 UTC, wangcj05 requested changes
@mandd It seems a couple of comments have not been addressed yet.

2023-06-26 16:18 UTC, wangcj05 commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +        melcIn = currentInputFiles[index]
I suggest to add a check inside the if statement, for example:
```python
if foundMelcorInp:
  raise IOError(f"Multiple Melcor input files are founded {inputFile} and {melgIn}, please check your inputs, only one of input is accepted")
```

2023-06-26 16:18 UTC, wangcj05 commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +      if inputFile.getExt() in self.getInputExtension():
It seems this issue has not been addressed yet.

2023-06-26 16:18 UTC, wangcj05 commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    melcOut = 'OUTPUT_MELCOR'
could you address this issue also?

2023-09-22 21:41 UTC, mandd commented
This PR is good to go I think

2023-09-25 16:09 UTC, wangcj05 commented on tests/framework/CodeInterfaceTests/test_melcor_interface.xml
> -          <revision author="alfoa" date="2020-10-31">Added csv xml node in the Code block for showing how to use it.</revision>
These two lines should not be removed.

2024-04-11 23:02 UTC, alfoa commented on ravenframework/Models/PostProcessors/SubdomainBasicStatistics.py
> +                                       f"of the input space of DataObject {inputs[-1].name}!"))
self.name is set to the attribute ``name'' (in the XML) in the base type class. It will return the name of the data object. (Tried)

2025-04-02 16:14 UTC, mandd commented
@wangcj05 and @alfoa : comments have been addressed

2025-04-02 20:25 UTC, alfoa requested changes

2025-04-02 20:25 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    return self.varList, self.melcorPlotFile, self.melcorOutFile
```suggestion
```
readMoreXML does not return anything...the data are stored in the "self"

2025-04-02 20:25 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +        melcIn = currentInputFiles[index]
this are the same? why we need to return a tuple if the melgIn and melcIn are the same?

2025-04-02 20:25 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +      Output the parsed results into a CSV file
```suggestion
      Store the output results in a dictionary that will be returned to RAVEN 
```

2025-04-02 20:25 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    print(self.varList)
```suggestion
```

2025-04-02 20:25 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    outputToRead.close()
if you return early (in the try except) this file is never closed. 

I would use the construct 
```
   with open(os.path.join(workingDir,self.melcorOutFile),"r") as outputToRead:

    ------ operations here ----
```

2025-04-02 20:25 UTC, alfoa commented on ravenframework/contrib/melcorTools/melcorTools.py
> +  Last update on October 14, 2022
```suggestion
  DISCLAIMER: 
    THIS MODULE IS AN EXTERNAL MODULE NOT MAINTAINED BY RAVEN TEAM.
    ORIGINAL MODULE AVAILABLE AT: https://github.com/mattdon/MELCOR_pyPlot
  
  MELCOR FORMAT SUPPORT MODULE
  Created on March 28, 2017
  Last update on October 14, 2022
```

2025-04-02 21:55 UTC, alfoa commented on doc/user_manual/code_interfaces/melcor.tex
> +
```suggestion
\nb

```

PS. This sentence is not complete?

2025-04-02 22:38 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +        if foundMelcorInp:
foundMelcorInp is not set?

2025-04-02 22:40 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +        melgIn = currentInputFiles[index]
```suggestion
```

2025-04-02 22:41 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    return melgIn, melcIn
```suggestion
    return melcIn
```

2025-04-02 22:41 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +          raise IOError(f"Multiple Melcor input files are found {inputFile} and {melgIn}, please check your inputs, only one of input is accepted")
```suggestion
          raise IOError(f"Multiple Melcor input files are found {inputFile} and {melcIn}, please check your inputs, only one of input is accepted")
```

2025-04-02 22:41 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +      @ Out, (melgIn,melcIn), tuple, tuple containing Melgen and Melcor input files
```suggestion
      @ Out, melcIn, str,  Melcor input file
```

2025-04-02 22:42 UTC, alfoa commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
>      melcin,melgin = self.findInps(inputFiles)
```suggestion
    melcin = self.findInps(inputFiles)
```

2025-04-03 13:46 UTC, alfoa commented on doc/user_manual/code_interfaces/melcor.tex
> +\nb
is this "Note" needed?

2025-04-03 13:48 UTC, alfoa commented on doc/user_manual/code_interfaces/melcor.tex
> +The second one (i.e., \xmlNode{MelcorOutput}) specifies the name of the MELCOR message file.
it seems that the interface accepts also a node "variables"

2025-04-03 15:34 UTC, mandd commented on doc/user_manual/code_interfaces/melcor.tex
> +\nb
removed

2025-04-03 15:34 UTC, mandd commented on doc/user_manual/code_interfaces/melcor.tex
> +The second one (i.e., \xmlNode{MelcorOutput}) specifies the name of the MELCOR message file.
added

2025-04-03 15:34 UTC, mandd commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +      (e.g. in RELAP5 would be the keyword "********")
fixed

2025-04-04 20:57 UTC, alfoa approved these changes

2025-04-15 15:36 UTC, wangcj05 requested changes
@mandd I have a couple of comments for you to consider.

2025-04-15 15:36 UTC, wangcj05 commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    like MELCOR 2.2x, MELCOR 1.86, MELCOR for fusion applications
By the way, is there any way that we can check the MELCOR version?

2025-04-15 15:36 UTC, wangcj05 commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
>  class Melcor(CodeInterfaceBase):
Can we make Melcor interface inherit from GenericCodeInterface? I saw you are using GenericParser already.

2025-04-16 14:22 UTC, mandd commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
>             Andrea Alfonsi (INL)
Fixed

2025-04-16 15:01 UTC, mandd commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    returnCommand = [('serial',melgCommand + ' && ' + melcCommand +' ow=o ')],melcOut
i do not think so

2025-04-16 15:03 UTC, mandd commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    goodWord  = "Normal termination"   # This is for MELCOR 2.2 (todo: list for other MELCOR versions)
moved to init

2025-04-16 15:51 UTC, mandd commented on doc/user_manual/code_interfaces/melcor.tex
> +The second one (i.e., \xmlNode{MelcorOutput}) specifies the name of the MELCOR message file.
I have added a small additional description, now that we have a MELCOR user in the group we will gather more experience on this interface

2025-04-16 15:59 UTC, mandd commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    self.melcorOutFile  = [var.strip() for var in melNode.text.split(",")][0]
Fixed

2025-04-16 15:59 UTC, mandd commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    parser.writeNewInput(currentInputFiles,origFiles)
see comment above

2025-04-17 15:03 UTC, moosebuild commented
Job [Test mac](https://civet.inl.gov/job/2823509/) on de9ceac : invalidated by @joshua-cogliati-inl

failed in set python environment with download failure

2025-04-17 17:05 UTC, alfoa commented
@mandd  I would also move the MELCOR test(s) in its dedicated folder (for better organization of the CodeInterface test folder)

2025-04-21 17:50 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/2829144/) on 1e8fbe9 : invalidated by @joshua-cogliati-inl

restarted civet

2025-04-23 19:47 UTC, wangcj05 requested changes
@mandd Some minor comments for you to consider.

2025-04-23 19:47 UTC, wangcj05 commented on tests/framework/CodeInterfaceTests/test_melcor_interface.xml
> +      <created>2023-02-20</created>
I think we should not change the author here.

2025-04-23 19:47 UTC, wangcj05 commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    indexes  = []
It seems variable "indexes" is not used.

2025-04-23 22:01 UTC, mandd reviewed
addressing latest comments

2025-04-23 22:01 UTC, mandd commented on ravenframework/CodeInterfaceClasses/MELCOR/melcorCombinedInterface.py
> +    indexes  = []
removed

2025-04-24 14:51 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/229651/) on eeebb8c : invalidated by @wangcj05

timeout and fetch issue

2025-04-24 15:22 UTC, moosebuild commented
Job [Test Ubuntu 18 PIP](https://civet.inl.gov/job/2834215/) on eeebb8c : invalidated by @mandd

2025-04-25 14:44 UTC, moosebuild commented
Job [Test CentOS 7](https://civet.inl.gov/job/2834209/) on eeebb8c : invalidated by @mandd

2025-04-25 14:44 UTC, moosebuild commented
Job [Test Fedora Odd](https://civet.inl.gov/job/2834212/) on eeebb8c : invalidated by @mandd

2025-04-25 14:45 UTC, moosebuild commented
Job [Test Ubuntu 18-2 Python 3](https://civet.inl.gov/job/2834214/) on eeebb8c : invalidated by @mandd

2025-04-25 14:45 UTC, moosebuild commented
Job [Test Ubuntu 16](https://civet.inl.gov/job/2834213/) on eeebb8c : invalidated by @mandd

2025-04-25 14:46 UTC, moosebuild commented
Job [Test qsubs sawtooth](https://civet.inl.gov/job/2834206/) on eeebb8c : invalidated by @mandd

2025-04-25 14:46 UTC, moosebuild commented
Job [Test mac](https://civet.inl.gov/job/2834205/) on eeebb8c : invalidated by @mandd

2025-04-25 22:17 UTC, moosebuild commented
Job [Test Ubuntu 16](https://civet.inl.gov/job/2840244/) on 05c2303 : invalidated by @mandd

2025-04-25 22:18 UTC, moosebuild commented
Job [Test qsubs sawtooth](https://civet.inl.gov/job/2840237/) on 05c2303 : invalidated by @mandd

2025-04-25 22:52 UTC, moosebuild commented
Job [Test CentOS 8](https://civet.inl.gov/job/2840241/) on 05c2303 : invalidated by @wangcj05

restart since there is a fix for the failure merged into devel

2025-04-25 22:53 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/2840239/) on 05c2303 : invalidated by @wangcj05

restart

2025-04-26 00:15 UTC, moosebuild commented
Job [Test Ubuntu 16](https://civet.inl.gov/job/2840244/) on 05c2303 : invalidated by @wangcj05

2025-04-28 05:30 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/2840239/) on 05c2303 : invalidated by @wangcj05

2025-04-28 05:31 UTC, moosebuild commented
Job [Test qsubs sawtooth](https://civet.inl.gov/job/2840237/) on 05c2303 : invalidated by @wangcj05

2025-04-28 05:31 UTC, moosebuild commented
Job [Test Ubuntu 16](https://civet.inl.gov/job/2840244/) on 05c2303 : invalidated by @wangcj05

2025-04-28 14:30 UTC, moosebuild commented
Job [Test Ubuntu 16](https://civet.inl.gov/job/2840244/) on 05c2303 : invalidated by @mandd

2025-04-28 19:48 UTC, moosebuild commented
Job [Test Ubuntu 16](https://civet.inl.gov/job/2840244/) on 05c2303 : invalidated by @joshua-cogliati-inl

Timeout tests/framework/ROM/TimeSeries/ARMA/ZeroFilter

2025-04-29 15:27 UTC, wangcj05 approved these changes
changes are good.

2025-04-29 15:32 UTC, merged