Subdomain basic statistics .
idaholab/raven pull request #2119
Opened 2023-05-22 19:10 UTC by aalfonsi

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #1923 

##### What are the significant changes in functionality due to this change request?
Added a new post processor to compute subdomain basic statistics leveraging RAVEN basic statistics. 

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2023-05-22 19:32 UTC, aalfonsi commented on ravenframework/Models/PostProcessors/BasicStatistics.py
> +    print(outputSet)
```suggestion
```

2023-05-24 14:12 UTC, mandd requested changes

2023-05-24 14:15 UTC, mandd commented
I have left my initial set of comments. One of my main questions is why a new PP class was added rather than extending the directly the basic statistics?

2023-05-24 14:20 UTC, aalfonsi commented on doc/user_manual/PostProcessors/SubdomainBasicStatistics.tex
> +The results will be associated to the mid-point of each point. For the example above:
```suggestion
The results will be associated to the mid-point of each cell. For the example above:
```

2023-05-24 14:28 UTC, aalfonsi commented on doc/user_manual/PostProcessors/SubdomainBasicStatistics.tex
> +\begin{itemize}
The interval of the fist grid is
[10,100] with 2 steps:
`|---------|---------|`
`10        55       100`
midpoints:
 `------|--------|------`
 `      32.5     77.5 `

2023-05-24 14:29 UTC, aalfonsi commented on doc/user_manual/raven_user_manual.tex
> +
I added a comment at the begin of the command:
```the following allows for 8 levels list nesting```

This allows to add an additional level of nesting for the "itemize" command

2023-05-24 14:37 UTC, aalfonsi commented on doc/user_manual/sampler.tex
> +}
yeah probably not the right location. Moved to postprocessors.tex

2023-05-24 14:38 UTC, aalfonsi commented on doc/user_manual/sampler.tex
> +{
Typo. CFD -> CDF (Cumulative Dist Function)

2023-05-24 15:58 UTC, aalfonsi commented on doc/user_manual/PostProcessors/SubdomainBasicStatistics.tex
> +The results will be associated to the mid-point of each point. For the example above:
fixed

2023-05-24 16:18 UTC, aalfonsi commented
> I have left my initial set of comments. One of my main questions is why a new PP class was added rather than extending the directly the basic statistics?

@mandd addressed your comments. The reason is mostly because it would have required an additional refactoring of the basic statistics and it is already quite complex. The advantage of having this PP is that the computation is encapsulated in the BasicStatistics and, in the future, the calculation for each "cell" can be parallelized if needed.

2023-05-25 20:31 UTC, mandd approved these changes

2023-05-25 20:31 UTC, mandd commented on doc/user_manual/PostProcessors/SubdomainBasicStatistics.tex
> +\begin{itemize}
gotcha

2023-05-25 20:57 UTC, wangcj05 commented
Hi @aalfonsi: Is it possible that the subdomain information (the grid lower and upper bound) also get stored in the DataObjects, for example in the metadata? I would recommend to preserve this information in the output DataObject.

2023-05-25 22:04 UTC, aalfonsi commented
> Hi @aalfonsi: Is it possible that the subdomain information (the grid lower and upper bound) also get stored in the DataObjects, for example in the metadata? I would recommend to preserve this information in the output DataObject.

@wangcj05 can you open an issue and I can address it in a followup MR?

2023-05-25 22:09 UTC, merged