[WIP] Workshop2024 merge
idaholab/raven pull request #2328
Opened 2024-06-04 20:06 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

2024-06-21 21:49 UTC, wangcj05 commented
@joshua-cogliati-inl It seems there is some problem with IDW rom: 
<img width="1067" alt="image" src="https://github.com/idaholab/raven/assets/7321071/e61985ac-dc0a-4b9c-a560-cd4b591cefe1">

Do you have time to take a look at it? You can check test at:  

<img width="863" alt="image" src="https://github.com/idaholab/raven/assets/7321071/ef97d677-b4cf-4076-b14a-00d8de9e340b">

2024-06-24 14:41 UTC, joshua-cogliati-inl commented
> @joshua-cogliati-inl It seems there is some problem with IDW rom: 

Hm, I wonder if commenting out line 234 in `crow/include/utilities/ND_Interpolation_Functions.h` would fix it.
(That is `virtual ~InverseDistanceWeighting() {};` )

@j-bryan (Any ideas?)

2024-06-24 18:06 UTC, j-bryan commented
@joshua-cogliati-inl I tried commenting out that line, rebuilding RAVEN, and running the test, and I still got that warning.

2024-07-10 21:01 UTC, joshua-cogliati-inl requested changes
This pull request adds workshop materials, but it also makes changes in ravenframework (especially in Samplers), however, this is not explained in the Pull Request Description or in the linked Issue/Task.

The workshop additions and the workshop example additions look fine (tho' some of the powerpoint files are on the big side).

2024-07-10 21:43 UTC, Jimmy-INL commented on doc/workshop/SparseSensing/SparseSensing.pptx
I have removed few slides, but it is still 33 MB. I cannot further reduce it @joshua-cogliati-inl

2024-07-10 23:14 UTC, alfoa commented on doc/workshop/SparseSensing/SparseSensing.pptx
To reduce the size, you can make power poin compress the pictures (for display usage) (maybe it does not impact the quality too much):
<img width="143" alt="Screenshot 2024-07-10 at 5 12 19 PM" src="https://github.com/idaholab/raven/assets/9202671/5ac370ab-1633-426f-9f31-183ba094d13c">

2024-07-11 14:18 UTC, joshua-cogliati-inl commented on doc/workshop/SparseSensing/SparseSensing.pptx
For what it is worth, using compress with HD shrinks this by about a third, and "print" shrinks it to about half.

2024-07-11 14:19 UTC, joshua-cogliati-inl reviewed
The merge fixed the extra changes, so I no longer think this needs changes.

2024-07-11 14:20 UTC, joshua-cogliati-inl reviewed
I think it would be worth trying to compress some of the powerpoint presentations.

2024-07-11 14:41 UTC, wangcj05 commented on doc/workshop/advancedSampling/scripts/conv_data.xlsx
This is used in the slides for comparison.

2024-07-11 14:57 UTC, wangcj05 commented
@joshua-cogliati-inl FYI, I have reduced the sizes of slides based on your suggestion using `print` option.

2024-07-11 16:36 UTC, wangcj05 commented
This PR only touches workshop materials, and there is no source code updates in this PR. Since HPC is under maintenance, the Test qsubs sawtooth can be skipped in this PR. Once other tests are green, this PR can be merged.

2024-07-11 16:56 UTC, merged