Alfoa/formatscript
idaholab/raven pull request #895
Opened 2019-01-16 00:22 UTC by alfoa

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Ref. #655 

##### What are the significant changes in functionality due to this change request?
This PR add a script to reformat the code and the docstrings to a RAVEN standard.
It can be used as utility function by the developers to be sure that modules and files are 
consistent with the Standard

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

2019-01-25 15:47 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/276235/) on 2a034f1 : invalidated by @alfoa

new machine options....re-testing

2019-10-16 17:00 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/410650/) on 4cca57e : invalidated by @PaulTalbot-INL

Windows test machine had crashed.

2019-10-16 20:52 UTC, PaulTalbot-INL submitted a review, later dismissed
A few comments with quite minor improvement requests.

2021-11-12 04:31 UTC, aalfonsi commented on scripts/fix_raven_docstrings.py
> +    be limited in the maxColumns number
fixed

2021-11-12 05:15 UTC, aalfonsi commented
@PaulTalbot-INL @wangcj05 @mandd @joshua-cogliati-inl

2021-11-12 17:56 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/886585/) on a982d31 : invalidated by @wangcj05

fetch failed.

2021-11-12 18:26 UTC, wangcj05 requested changes
some minor comments for your consideration

2021-11-12 18:26 UTC, wangcj05 commented on scripts/fix_raven_docstrings.py
> +      outputLines.append(line)
why use 'line' here? not 'indentedLine'?

2021-11-12 18:26 UTC, wangcj05 commented on scripts/fix_raven_docstrings.py
> +      breakIndex = quoteIndent+8
What is the purpose for line 52? 'breakIndex' is reassigned in line 53.

2021-11-14 05:03 UTC, aalfonsi commented
@wangcj05  addressed

2021-11-15 16:13 UTC, moosebuild commented
Job [Test qsubs falcon](https://civet.inl.gov/job/888880/) on 7504e9e : invalidated by @joshua-cogliati-inl

checking civet

2021-12-18 05:50 UTC, moosebuild commented
Job [Test qsubs falcon](https://civet.inl.gov/job/888880/) on 7504e9e : invalidated by @aalfonsi

2021-12-18 05:50 UTC, aalfonsi commented
@wangcj05 @joshua-cogliati-inl this is ready to be merged

2021-12-18 06:09 UTC, aalfonsi commented
@joshua-cogliati-inl @wangcj05 I also fixed the doc issue that presumably made "development" doc step fail

2021-12-18 07:29 UTC, moosebuild commented
Job [Test qsubs falcon](https://civet.inl.gov/job/919211/) on f770775 : invalidated by @aalfonsi

2022-01-04 15:48 UTC, moosebuild commented
Job [Mingw Test](https://civet.inl.gov/job/919213/) on f770775 : invalidated by @wangcj05

2022-01-04 15:51 UTC, wangcj05 approved these changes
This PR looks good to me.

2022-01-04 19:31 UTC, wangcj05 commented
PR is good, and checklist is satisfied. PR can be merged.

2022-01-04 19:35 UTC, merged

2022-01-04 19:35 UTC, wangcj05 commented
@aalfonsi Thanks for your contribution, I have merged your PR.